# Generated by Django 5.0.7 on 2026-01-07 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='suscriptor',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
