"""Add slugs and backfill them for existing rows.

We store curated images in Git under MULTIMEDIA TEATRO OCULTO/ and resolve them
by model slug, so legacy rows need slugs without manual re-saving.
"""

# Generated by Django 5.0.7 on 2026-03-04 16:13

from django.db import migrations, models
from django.utils.text import slugify


def _backfill_slugs(apps, schema_editor):
    Iniciativa = apps.get_model('web', 'Iniciativa')
    Obra = apps.get_model('web', 'Obra')
    Equipo = apps.get_model('web', 'Equipo')

    def backfill(model, source_attr: str, fallback: str):
        existing = set(
            model.objects.exclude(slug='').values_list('slug', flat=True)
        )

        for obj in model.objects.filter(slug='').order_by('pk'):
            raw = (getattr(obj, source_attr, '') or '').strip()
            base = slugify(raw) or fallback
            candidate = base[:220]

            if candidate in existing:
                candidate = f"{candidate[:200]}-{obj.pk}"

            obj.slug = candidate
            obj.save(update_fields=['slug'])
            existing.add(candidate)

    backfill(Iniciativa, 'title', 'iniciativa')
    backfill(Obra, 'title', 'obra')
    backfill(Equipo, 'name', 'equipo')


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_update_obra_sobre_tabaco_synopsis'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='slug',
            field=models.SlugField(blank=True, max_length=220),
        ),
        migrations.AddField(
            model_name='iniciativa',
            name='slug',
            field=models.SlugField(blank=True, max_length=220),
        ),
        migrations.AddField(
            model_name='obra',
            name='slug',
            field=models.SlugField(blank=True, max_length=220),
        ),
        migrations.RunPython(_backfill_slugs, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='iniciativa',
            name='category',
            field=models.CharField(choices=[('Creación', 'Creación'), ('Formación', 'Formación de audiencia y comunidad'), ('Comunidad', 'Formación de audiencia')], max_length=20),
        ),
    ]
