# Generated by Django 5.0.7 on 2026-03-04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_equipo_slug_iniciativa_slug_obra_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='slug',
            field=models.SlugField(blank=True, db_index=True, max_length=220),
        ),
        migrations.AlterField(
            model_name='iniciativa',
            name='slug',
            field=models.SlugField(blank=True, db_index=True, max_length=220),
        ),
        migrations.AlterField(
            model_name='obra',
            name='slug',
            field=models.SlugField(blank=True, db_index=True, max_length=220),
        ),
    ]
