"""
Django settings for teatro_project project.

Generated by 'django-admin startproject' using Django 5.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure-u^lr7&0n%s4v_zlm&b&$d7f^im=9gdymyg6(o+*6n+pjp+*66^',
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DEBUG", "1").lower() not in ("0", "false", "no", "off")

# ALLOWED_HOSTS can be provided as a comma-separated env var, e.g.
# ALLOWED_HOSTS=teatrooculto.cl,127.0.0.1
ALLOWED_HOSTS = os.environ.get("ALLOWED_HOSTS", "")
if ALLOWED_HOSTS:
    ALLOWED_HOSTS = [h.strip() for h in ALLOWED_HOSTS.split(",") if h.strip()]
else:
    ALLOWED_HOSTS = []

# Ensure the production host is allowed as a safe default when env is empty
if not ALLOWED_HOSTS:
    # include localhost, docker service name and the expected domain to avoid DisallowedHost during initial deploy
    ALLOWED_HOSTS = ["127.0.0.1", "localhost", "web", "teatrooculto.cl"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'web',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'teatro_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'web.context_processors.footer_lists',
            ],
        },
    },
]

WSGI_APPLICATION = 'teatro_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'es'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = '/static/'

# Static files and media configuration
# Where collectstatic will gather files for the web server to serve
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'static', BASE_DIR / 'MULTIMEDIA TEATRO OCULTO']

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Reverse proxy / HTTPS settings (for Nginx TLS termination)
if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    # Nginx already redirects HTTP->HTTPS; keep Django from double-redirect loops.
    SECURE_SSL_REDIRECT = False

    csrf_trusted_raw = os.environ.get('CSRF_TRUSTED_ORIGINS', '').strip()
    if csrf_trusted_raw:
        CSRF_TRUSTED_ORIGINS = [
            o.strip() for o in csrf_trusted_raw.split(',') if o.strip()
        ]
    else:
        # Safe default for initial deploy
        CSRF_TRUSTED_ORIGINS = ['https://teatrooculto.cl']

    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_SECURE = True


# Email
# - In DEBUG: print emails to console.
# - In production: use SMTP when EMAIL_HOST is provided.
EMAIL_HOST = os.environ.get('EMAIL_HOST', '').strip()
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '587'))
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '').strip()
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '').strip()

EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', '1').strip().lower() in {
    '1', 'true', 'yes', 'on'
}
EMAIL_USE_SSL = os.environ.get('EMAIL_USE_SSL', '0').strip().lower() in {
    '1', 'true', 'yes', 'on'
}
EMAIL_TIMEOUT = int(os.environ.get('EMAIL_TIMEOUT', '20'))

if DEBUG:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
else:
    EMAIL_BACKEND = (
        'django.core.mail.backends.smtp.EmailBackend'
        if EMAIL_HOST
        else 'django.core.mail.backends.console.EmailBackend'
    )

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Default from email used when sending site messages.
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'no-reply@teatrooculto.local')
